# Streamlit Secrets Template
# Copy this to your Streamlit Cloud secrets section

OPENAI_API_KEY = "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"
APP_ENVIRONMENT = "production"

# Optional configurations
# TESSERACT_PATH = "/usr/bin/tesseract"
# MAX_FILE_SIZE_MB = "15"
